apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-g43m
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dcen-tenant/rhtap-demo-app/hacbs-test-project-g43m@sha256:dc3e56f74bd513446e6ec32cf7c6866928e7252263f5c7df75b83972032a8577
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
