apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-g43m
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-g43m
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-g43m
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-g43m
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-g43m
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dcen-tenant/rhtap-demo-app/hacbs-test-project-g43m@sha256:dc3e56f74bd513446e6ec32cf7c6866928e7252263f5c7df75b83972032a8577
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
